import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Head";
import Footer from "@/components/Footer";
import {ClerkProvider} from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
      <div className="flex flex-col min-h-screen ">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
      </div>
          
      
    </ClerkProvider>
  );
}
