import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Head";
import Footer from "@/components/Footer";
import HomeVid1 from "@/components/HomeVid1";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
